name: Integration Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  integration:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install Clojure
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: latest
    
    - name: Cache Clojure dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          .cpcache
        key: ${{ runner.os }}-clojure-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-clojure-
    
    - name: Run integration tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: make test-integration
